import React, { useEffect, useRef } from "react";
import $ from "jquery";
import "datatables.net-dt/css/jquery.dataTables.min.css";

$.DataTable = require("datatables.net");

const data = [
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund F",
    type: "P",
    series: "F",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
  {
    name: "Sustainable Income 20/80 Fund A",
    type: "P",
    series: "A",
    date: "08/05/2022",
    assetClass: "Multi Asset Solutions",
    navPerUnit: "	9.23",
    navChange: "	-0.40",
  },
];

const DistributionsTable = () => {
  const tableRef = useRef(null);

  useEffect(() => {
    if (!$.fn.DataTable.isDataTable(tableRef.current))
      $(tableRef.current).DataTable({ paging: false });
  }, [tableRef]);

  return (
    <table ref={tableRef}>
      <thead>
        <tr>
          <th>Fund Name</th>
          <th>Type</th>
          <th>Series</th>
          <th>Nav Date</th>
          <th>Asset Class</th>
          <th>NAV Per Unit</th>
          <th>NAV Change(%)</th>
        </tr>
      </thead>
      <tbody>
        {data.map((el, idx) => {
          const {
            name,
            type,
            series,
            date,
            assetClass,
            navPerUnit,
            navChange,
          } = el;

          return (
            <tr key={"d" + idx}>
              <td>{name}</td>
              <td>
                <div className="tag blue">{type}</div>
              </td>
              <td>
                <div className="tag">{series}</div>
              </td>
              <td>{date}</td>
              <td>{assetClass}</td>
              <td>{navPerUnit}</td>
              <td>{navChange}</td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};

export default React.memo(DistributionsTable, () => true);
